concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}
env:
  GRADLE_ENTERPRISE_ACCESS_KEY: ${{ secrets.GE_ACCESS_TOKEN }}
  MAVEN_OPTS: -Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false -Dmaven.wagon.http.retryHandler.class=standard
    -Dmaven.wagon.http.retryHandler.count=3
jobs:
  Simple:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: liberica
        java-version: 17
    - continue-on-error: true
      name: Cache Maven packages
      uses: actions/cache@v4
      with:
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        path: ~/.m2
        restore-keys: ${{ runner.os }}-m2-
    - continue-on-error: true
      if: ${{ runner.os == 'Windows' }}
      name: Adjust network dynamic TCP ports range
      run: 'netsh int ipv4 set dynamicport tcp start=32768 num=32768

        netsh int ipv4 set dynamicport udp start=32768 num=32768

        netsh int ipv6 set dynamicport tcp start=32768 num=32768

        netsh int ipv6 set dynamicport udp start=32768 num=32768

        '
      shell: pwsh
    - continue-on-error: true
      if: ${{ runner.os == 'Linux' }}
      name: Adjust Linux kernel somaxconn
      run: sudo sysctl -w net.core.somaxconn=65535
      shell: bash
    - continue-on-error: true
      name: IT/UT Test
      run: 'mvn clean verify \

        -P with-integration-tests \

        -DskipUTs \

        -DintegrationTest.forkCount=2 \

        -pl integration-test \

        -am

        '
      shell: bash
    - continue-on-error: true
      if: failure()
      name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: standalone-log-java${{ matrix.java }}-${{ runner.os }}
        path: integration-test/target/cluster-logs
        retention-days: 1
    strategy:
      fail-fast: false
      matrix:
        os:
        - ubuntu-latest
        - windows-latest
      max-parallel: 15
name: Cluster IT - 1C1D
on:
  repository_dispatch:
    types: trigger-ga___cluster-it-1c1d.yml
