concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}
env:
  GRADLE_ENTERPRISE_ACCESS_KEY: ${{ secrets.GE_ACCESS_TOKEN }}
  MAVEN_OPTS: -Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false -Dmaven.wagon.http.retryHandler.class=standard
    -Dmaven.wagon.http.retryHandler.count=3
jobs:
  Simple:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v4
      with:
        distribution: liberica
        java-version: ${{ matrix.java }}
    - continue-on-error: true
      name: IT/UT Test
      run: 'mvn clean verify \

        -P with-integration-tests \

        -DskipUTs \

        -DintegrationTest.forkCount=6 -DConfigNodeMaxHeapSize=1024 -DDataNodeMaxHeapSize=1024
        \

        -pl integration-test \

        -am -PClusterIT

        '
      shell: bash
    - continue-on-error: true
      if: failure()
      name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: cluster-log-java${{ matrix.java }}-${{ runner.os }}
        path: integration-test/target/cluster-logs
        retention-days: 1
    strategy:
      fail-fast: false
      matrix:
        java:
        - 8
        - 11
        - 17
      max-parallel: 20
name: Cluster IT - 1C3D
on:
  repository_dispatch:
    types: trigger-ga___cluster-it-1c3d.yml
