concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}
env:
  GRADLE_ENTERPRISE_ACCESS_KEY: ${{ secrets.GE_ACCESS_TOKEN }}
  MAVEN_OPTS: -Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false -Dmaven.wagon.http.retryHandler.class=standard
    -Dmaven.wagon.http.retryHandler.count=3
jobs:
  auto-create-schema:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v4
      with:
        distribution: liberica
        java-version: ${{ matrix.java }}
    - continue-on-error: true
      name: IT Test
      run: 'mvn clean verify \

        -P with-integration-tests \

        -DskipUTs \

        -DintegrationTest.forkCount=1 -DConfigNodeMaxHeapSize=256 -DDataNodeMaxHeapSize=1024
        -DDataNodeMaxDirectMemorySize=768 \

        -DClusterConfigurations=${{ matrix.cluster }},${{ matrix.cluster }} \

        -pl integration-test \

        -am -PMultiClusterIT2AutoCreateSchema

        '
      shell: bash
    - continue-on-error: true
      if: failure()
      name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: cluster-log-auto-create-schema-java${{ matrix.java }}-${{ runner.os
          }}-${{ matrix.cluster1 }}-${{ matrix.cluster2 }}
        path: integration-test/target/cluster-logs
        retention-days: 30
    strategy:
      fail-fast: false
      matrix:
        cluster:
        - LightWeightStandaloneMode
        - ScalableSingleNodeMode
        - HighPerformanceMode
        java:
        - 17
        os:
        - ubuntu-latest
      max-parallel: 15
  manual-create-schema:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v4
      with:
        distribution: liberica
        java-version: ${{ matrix.java }}
    - continue-on-error: true
      name: IT Test
      run: 'mvn clean verify \

        -P with-integration-tests \

        -DskipUTs \

        -DintegrationTest.forkCount=1 -DConfigNodeMaxHeapSize=256 -DDataNodeMaxHeapSize=1024
        -DDataNodeMaxDirectMemorySize=768 \

        -DClusterConfigurations=${{ matrix.cluster1 }},${{ matrix.cluster2 }} \

        -pl integration-test \

        -am -PMultiClusterIT2ManualCreateSchema

        '
      shell: bash
    - continue-on-error: true
      if: failure()
      name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: cluster-log-manual-create-schema-java${{ matrix.java }}-${{ runner.os
          }}-${{ matrix.cluster1 }}-${{ matrix.cluster2 }}
        path: integration-test/target/cluster-logs
        retention-days: 30
    strategy:
      fail-fast: false
      matrix:
        cluster1:
        - LightWeightStandaloneMode
        - ScalableSingleNodeMode
        - HighPerformanceMode
        cluster2:
        - LightWeightStandaloneMode
        - ScalableSingleNodeMode
        - HighPerformanceMode
        java:
        - 17
        os:
        - ubuntu-latest
      max-parallel: 15
  subscription:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v4
      with:
        distribution: liberica
        java-version: ${{ matrix.java }}
    - continue-on-error: true
      name: IT Test
      run: 'mvn clean verify \

        -P with-integration-tests \

        -DskipUTs \

        -DintegrationTest.forkCount=1 -DConfigNodeMaxHeapSize=256 -DDataNodeMaxHeapSize=1024
        -DDataNodeMaxDirectMemorySize=768 \

        -DClusterConfigurations=${{ matrix.cluster1 }},${{ matrix.cluster2 }} \

        -pl integration-test \

        -am -PMultiClusterIT2Subscription

        '
      shell: bash
    - continue-on-error: true
      if: failure()
      name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: cluster-log-subscription-java${{ matrix.java }}-${{ runner.os }}-${{
          matrix.cluster1 }}-${{ matrix.cluster2 }}
        path: integration-test/target/cluster-logs
        retention-days: 30
    strategy:
      fail-fast: false
      matrix:
        cluster1:
        - LightWeightStandaloneMode
        - ScalableSingleNodeMode
        - HighPerformanceMode
        cluster2:
        - ScalableSingleNodeMode
        java:
        - 17
        os:
        - ubuntu-latest
      max-parallel: 15
name: Multi-Cluster IT
on:
  repository_dispatch:
    types: trigger-ga___pipe-it-2cluster.yml
