concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}
env:
  GRADLE_ENTERPRISE_ACCESS_KEY: ${{ secrets.GE_ACCESS_TOKEN }}
  MAVEN_OPTS: -Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false -Dmaven.wagon.http.retryHandler.class=standard
    -Dmaven.wagon.http.retryHandler.count=3
  PR_NUMBER: ${{ github.event.number }}
jobs:
  codecov:
    if: github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name
      == 'apache/iotdb' || github.event_name == 'push'
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Cache Maven packages
      uses: actions/cache@v4
      with:
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        path: ~/.m2
        restore-keys: ${{ runner.os }}-m2-
    - continue-on-error: true
      name: Test
      run: 'mvn -B -P with-code-coverage clean package -pl distribution,iotdb-client/cli,iotdb-client/session,iotdb-client/jdbc
        -am -Dtest.port.closed=true

        mvn -B -P with-code-coverage post-integration-test -pl code-coverage

        '
    - continue-on-error: true
      name: Upload coverage reports to codecov
      uses: codecov/codecov-action@v4
      with:
        files: ./code-coverage/target/jacoco-merged-reports/jacoco.xml
        token: ${{ secrets.CODECOV_TOKEN }}
  sonar:
    if: github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name
      == 'apache/iotdb' || github.event_name == 'push'
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: corretto
        java-version: 17
    - continue-on-error: true
      name: Cache Maven packages
      uses: actions/cache@v4
      with:
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        path: ~/.m2
        restore-keys: ${{ runner.os }}-m2-
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONARCLOUD_TOKEN }}
      name: SonarCloud Report
      run: 'mvn -B -P with-integration-tests,with-code-coverage verify sonar:sonar
        \

        -Dsonar.organization=apache \

        -Dsonar.projectKey=apache_iotdb \

        -Dsonar.host.url=https://sonarcloud.io \

        -Dsonar.token=${{ secrets.SONARCLOUD_TOKEN }} \

        -DskipTests -pl ''!distribution,!integration-test'' -am

        '
name: Sonar-Codecov
on:
  repository_dispatch:
    types: trigger-ga___sonar-codecov.yml
